language: ruby
rvm:
  - 2.7.1
before_script:
  - gem install awesome_bot
  - gem install danger
script:
  - awesome_bot README.md --allow-ssl --white-list travis-ci
  - danger
notifications:
  email:
    on_success: never
